application: northern-shield-780
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# [START handlers]
handlers:
- url: /img
  static_dir: img
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /.*
  script: main.app
# [END handlers]
  
libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest