application: ostapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# [START handlers]
handlers:
- url: /images
  static_dir: images
  
- url: /style
  static_dir: style
  
- url: /.*
  script: main.app
# [END handlers]
  
libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest